/**
 * Selector generation for the recorder.
 *
 * The hard part of authoring a tour is not writing copy — it is picking a
 * selector that still matches after the next deploy. This scores candidates by
 * how likely they are to survive: explicit test/tour hooks first, then stable
 * ids, then semantic attributes, and only as a last resort a positional path.
 */

/** Attributes that exist specifically to be targeted, in order of preference. */
const HOOK_ATTRS = [
  'data-tour',
  'data-testid',
  'data-test-id',
  'data-test',
  'data-cy',
  'data-qa',
  'data-automation-id',
];

/** Class names generated by CSS-in-JS / utility frameworks — never stable. */
const UNSTABLE_CLASS = /^(css-[a-z0-9]+|sc-[a-zA-Z0-9]+|jsx-\d+|[a-z]+-[a-f0-9]{5,}|_[\w-]{5,})$/;

/** Ids that look generated rather than authored. */
const UNSTABLE_ID = /(^|[-_:])(\d{3,}|[a-f0-9]{8,}|uid|uuid|react-aria|radix|headlessui|mui-)/i;

export interface SelectorCandidate {
  selector: string;
  /** 0–100. Above 70 is safe to ship; below 40 will probably break. */
  score: number;
  reason: string;
  /** How many elements this selector matches right now. */
  matches: number;
}

function escapeValue(value: string): string {
  if (typeof CSS !== 'undefined' && typeof CSS.escape === 'function') return CSS.escape(value);
  return value.replace(/["\\]/g, '\\$&');
}

function countMatches(selector: string, root: Document = document): number {
  try { return root.querySelectorAll(selector).length; } catch { return 0; }
}

function stableClasses(el: Element): string[] {
  return Array.from(el.classList).filter(
    (c) => c.length > 1 && !UNSTABLE_CLASS.test(c) && !c.startsWith('ot-'),
  );
}

function nthOfType(el: Element): number {
  const parent = el.parentElement;
  if (!parent) return 1;
  const siblings = Array.from(parent.children).filter((c) => c.tagName === el.tagName);
  return siblings.indexOf(el) + 1;
}

/** Shortest positional path from a stable ancestor, used only as a fallback. */
function pathSelector(el: Element, root: Document = document): string {
  const parts: string[] = [];
  let node: Element | null = el;
  let depth = 0;

  while (node && node.nodeType === 1 && depth < 6) {
    if (node.id && !UNSTABLE_ID.test(node.id)) {
      parts.unshift(`#${escapeValue(node.id)}`);
      break;
    }

    const tag = node.tagName.toLowerCase();
    if (tag === 'html' || tag === 'body') { parts.unshift(tag); break; }

    const classes = stableClasses(node);
    let part = classes.length > 0 ? `${tag}.${escapeValue(classes[0])}` : tag;

    const parent: Element | null = node.parentElement;
    if (parent) {
      const sameShape = Array.from(parent.children).filter(
        (c) => c.tagName === node!.tagName && (classes.length === 0 || c.classList.contains(classes[0])),
      );
      if (sameShape.length > 1) part += `:nth-of-type(${nthOfType(node)})`;
    }

    parts.unshift(part);
    node = parent;
    depth += 1;

    const candidate = parts.join(' > ');
    if (countMatches(candidate, root) === 1) break;
  }

  return parts.join(' > ');
}

/** Every viable selector for an element, best first. */
export function generateSelectors(el: Element, root: Document = document): SelectorCandidate[] {
  const candidates: SelectorCandidate[] = [];
  const add = (selector: string, score: number, reason: string): void => {
    const matches = countMatches(selector, root);
    if (matches === 0) return;
    // A selector that matches several elements is only usable with an index,
    // which is inherently more fragile — reflect that in the score.
    const adjusted = matches === 1 ? score : Math.max(10, score - 25);
    candidates.push({ selector, score: adjusted, reason, matches });
  };

  for (const attr of HOOK_ATTRS) {
    const value = el.getAttribute(attr);
    if (value) {
      add(`[${attr}="${escapeValue(value)}"]`, attr === 'data-tour' ? 100 : 92, `explicit ${attr} hook`);
    }
  }

  if (el.id) {
    const stable = !UNSTABLE_ID.test(el.id);
    add(`#${escapeValue(el.id)}`, stable ? 85 : 45, stable ? 'element id' : 'id looks generated');
  }

  const name = el.getAttribute('name');
  if (name) add(`${el.tagName.toLowerCase()}[name="${escapeValue(name)}"]`, 78, 'form field name');

  const role = el.getAttribute('role');
  const ariaLabel = el.getAttribute('aria-label');
  if (role && ariaLabel) {
    add(`[role="${escapeValue(role)}"][aria-label="${escapeValue(ariaLabel)}"]`, 74, 'role + aria-label');
  } else if (ariaLabel) {
    add(`[aria-label="${escapeValue(ariaLabel)}"]`, 70, 'aria-label');
  }

  const classes = stableClasses(el);
  if (classes.length > 0) {
    const tag = el.tagName.toLowerCase();
    add(`${tag}.${classes.map(escapeValue).join('.')}`, 55, 'tag + stable classes');
    if (classes.length > 1) add(`.${escapeValue(classes[0])}`, 40, 'single class');
  }

  const path = pathSelector(el, root);
  if (path) add(path, 28, 'structural path (fragile — add a data-tour attribute)');

  return candidates
    .filter((c, i, all) => all.findIndex((o) => o.selector === c.selector) === i)
    .sort((a, b) => b.score - a.score);
}

export interface BestSelector {
  selector: string;
  score: number;
  reason: string;
  /** Lower-scored alternatives, usable as a `selector: []` fallback chain. */
  fallbacks: string[];
  /** Visible text, offered as a `target.text` fallback. */
  text?: string;
}

export function bestSelector(el: Element, root: Document = document): BestSelector | null {
  const candidates = generateSelectors(el, root);
  if (candidates.length === 0) return null;

  const [best, ...rest] = candidates;
  const text = (el.textContent ?? '').replace(/\s+/g, ' ').trim();

  return {
    selector: best.selector,
    score: best.score,
    reason: best.reason,
    fallbacks: rest.filter((c) => c.score >= 40).slice(0, 2).map((c) => c.selector),
    text: text.length > 0 && text.length <= 60 ? text : undefined,
  };
}

/** Check a set of selectors against the live page. Powers `lint-selectors`. */
export function auditSelectors(
  selectors: string[],
  root: Document = document,
): Array<{ selector: string; matches: number; ok: boolean; note?: string }> {
  return selectors.map((selector) => {
    const matches = countMatches(selector, root);
    if (matches === 0) return { selector, matches, ok: false, note: 'no element matches' };
    if (matches > 1) return { selector, matches, ok: true, note: `matches ${matches} elements; add target.index` };
    return { selector, matches, ok: true };
  });
}
